### ISSUE TITLE
Cannot access the main domain

### ISSUE THREAD

**Issue by weblikero** [ashokgelal/townhouse#1]
Hi there,

Very good tutorial, but still having a problem in accessing the main domain.

I'm able to access the tenants websites, but the main domain not.

any advice on this would be greatly appreciated.

Thank you

**Comment by ashokgelal** [comment]
I can access it just fine. What are you using to serve your app? Valet? Homestead?

**Comment by weblikero** [comment]
Hi, I use Valet  .

**Comment by muser83** [comment]
@weblikero try changing the tld-name for valet to another one different to .dev
Chrome have issues with .dev and .app tld-names.
I am using "valet domain localhost"

**Comment by hakanersu** [comment]
i think its related to tenancy.php#L134 config.
```
  /**
         * Abort application execution in case no hostname was identified. This will throw a
         * 404 not found in case the tenant hostname was not resolved.
         */
        'abort-without-identified-hostname' => true,
```

**Comment by Astriel** [comment]
@hakanersu : Got exactly the same issue, you save my day !
