### ISSUE TITLE
Error while creating tenant

### ISSUE THREAD

**Issue by ufuksevki** [ashokgelal/townhouse#14]
When I try to create admin user for tenant I get the below error:

Method Illuminate\Database\Query\Builder::assignRole does not exist.

**Comment by rashmika018** [comment]
tenancy>php artisan tenant:create boise boise@example.com

   Symfony\Component\Debug\Exception\FatalThrowableError  : Class 'Hyn\Tenancy\Models\Customer' not found

  at tenancy\app\Console\Commands\CreateTenant.php:46
    42|     }
    43|
    44|     private function tenantExists($name, $email)
    45|     {
  > 46|         return Customer::where('name', $name)->orWhere('email', $email)->exists();
    47|     }
    48|
    49|     private function registerTenant($name, $email)
    50|     {

  Exception trace:

  1   App\Console\Commands\CreateTenant::tenantExists("boise", "boise@example.com")
      tenancy\app\Console\Commands\CreateTenant.php:27

  2   App\Console\Commands\CreateTenant::handle()
      tenancy\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php:29

  Please use the argument -v to see more details.

tenancy>
