### ISSUE TITLE
New realease of tenancy (5.2 - no longer Customer model)

### ISSUE THREAD

**Issue by probonodecatalonia** [ashokgelal/townhouse#16]
Hi Ashok,

I have started a new project based on your tutorial (Great by the way...bravo), but noticed that recently 5.2 of tenancy package was released and they did a big change in the package.
The Customer model no longer present.
Will you update the tutorial? Can you give some hints on this? 

Big thanks to you.

**Comment by kaoussi** [comment]
Check this link: https://laravel-tenancy.com/docs/hyn/5.2/upgrade-from-5.1

They have some instructions on how to handle migration from 5.1 version of hyn/multi-tenant

I hope it helps.

**Comment by andrewbrooksie** [comment]
I am having this issue as well.

From the documentation it recommends to make sure to copy the customers model to your code base before upgrading to 5.2.

My roadblock to this solution is I have no existing code base to get the model from as I am creating a new project from scratch.

Should I downgrade to 5.1 to grab the customers model, upgrade to 5.2, then re-implement the customers model?

**Comment by colinmackinlay** [comment]
I've submitted a PR https://github.com/ashokgelal/townhouse/pull/17 with fixes for that. Hope that helps.

**Comment by mpchean** [comment]
Hi Colin:  I cloned your branch, but I'm getting a new issue when I try to use composer install.  

> @php artisan package:discover

In TenancyProvider.php line 66:

  Undefined index: customer


Script @php artisan package:discover handling the post-autoload-dump event returned with error code 1

C:\xampp\htdocs\townhouse>php artisan tenant:create boise boise@example.com

In TenancyProvider.php line 66:

  Undefined index: customer

**Comment by colinmackinlay** [comment]
Not certain what is causing this but most likely seems to be that TenancyProvider.php which is part of hyn/multitenant is an old version as it refers to customer and all references to that have gone in 5.2

My patch is to the tutorial so it works with Laravel 5.6 and Hyn 5.2. 

Seems to me that you've somehow got an earlier version of Hyn installed
