### ISSUE TITLE
Can't access main domain or any of the sub domains on Ubuntu.

### ISSUE THREAD

**Issue by nathansiafa** [ashokgelal/townhouse#2]
I'm on Ubuntu and I have followed of the steps through Part 1. But when I run my server using **php artisan serve ** I get this error message:

> Sorry, the page you are looking for could not be found.

Is there a way I can get this working on ubuntu or do I need to get a Macbook?

**Comment by ashokgelal** [comment]
Not a MacBook but I'd definitely recommend using Valet for serving your web app.

**Comment by nathansiafa** [comment]
I have install valet on ubuntu I'm still experiencing the same problem.

**Comment by michaeldalyuk** [comment]
I am having the same problem. Any idea on what could be causing it?

**Comment by nathansiafa** [comment]
@michealdalyuk what OS are you working on?

**Comment by mnuhell** [comment]
@nathansiafa I had the same error in the tenancy.php files i have this config `'abort-without-identified-hostname' => false,`

**Comment by hakanersu** [comment]
I had same problem and yes it is about ```'abort-without-identified-hostname' => false,``` 

Also i add below code to RouteServiceProvider.php, im not sure best or right way to do but its works for now;

```php
public function map()
{
    $this->mapApiRoutes();

    $this->mapWebRoutes();

    $this->mapMainRoutes();

    $this->mapTenantRoutes();
}

/**
 * Define the "web" routes for the application.
 *
 * These routes all receive session state, CSRF protection, etc.
 *
 * @return void
 */
protected function mapWebRoutes()
{
    Route::middleware('web')
         ->namespace($this->namespace)
         ->group(base_path('routes/web.php'));
}

protected function mapTenantRoutes()
{
    if (TenancyFacade::customer()) {
        Route::middleware(['web', 'tenancy.enforce'])
            ->namespace($this->namespace)
            ->group(base_path('routes/tenant.php'));
    }
}

protected function mapMainRoutes()
{
    if ($this->isMainHost()) {
        Route::middleware('web')
        ->namespace($this->namespace)
            ->group(base_path('routes/main.php'));
    }
}

private function isMainHost()
{
    $base = config('app.url_base');
    $host = request()->getHttpHost();

    return $base === $host || "www.{$base}" === $host;
}
```

**Comment by gkarugi** [comment]
@hakanersu Where have you defined the tenancy.enforce middleware?

**Comment by hakanersu** [comment]
@gkarugi 
https://github.com/ashokgelal/townhouse/blob/08ef0e3b700a8bcd7e29116d40298766136f11bf/app/Http/Middleware/EnforceTenancy.php#L1 and https://github.com/ashokgelal/townhouse/blob/08ef0e3b700a8bcd7e29116d40298766136f11bf/app/Http/Kernel.php#L60
