### ISSUE TITLE
How to make it support external websites/domains

### ISSUE THREAD

**Issue by damms005** [ashokgelal/townhouse#3]
Thank you for the great work with this townhouse project!

I want to ask a question that is fundamental to Laravel Tenancy, so that I can know what to expect of townhouse. My question is:

Does Laravel Tenancy (and by extension, townhouse) provide support for external websites/domains?

For example, if I host this Laravel Tenancy app on www.my-saas-domain.com and I have 3 clients from different countries that want my service hosted at www.my-saas-domain.com to be available on their already existing websites, and their websites are www.flamingo.com, www.cupcakes.com, and the third client has his website at www.client3.com:
1. Is this the whole point to Laravel Tenancy/townhouse and can it be handled like such?
2. OR must I host them on my site and thus simply give them admin logins and all?
3. OR is this what services like [Cleaver](https://getcleaver.com) provides and must I use such a service to achieve the above?

Thanks

**Comment by ashokgelal** [comment]
Laravel Tenancy and Cleaver should help you, yes, but you have to do a little bit of manual work yourself. I've not tried this myself but what could work is to change FQDNs for each tenant manually in your system database and then point all the domains to your main server. This is more of a domain aliasing than hosting 3 different apps on 3 different servers (which completely defeats the purpose of having a multi-tenant app in a way). Hope that answers your question.
