### ISSUE TITLE
Database [tenant] not configured.

### ISSUE THREAD

**Issue by mnuhell** [ashokgelal/townhouse#4]
Hi, after create all post How create Milti-tenant all work fine but when reset password show an error 
`Database [tenant] not configured.` 
Laravel: 5.5
multi-tenant: 5.0

**Comment by ashokgelal** [comment]
Make sure the reset url is generated properly as mentioned in this part: https://medium.com/@ashokgelal/a-full-featured-multi-tenant-app-with-laravel-part-4-tenancy-aware-authentication-e0ee37270bc8

**Comment by mnuhell** [comment]
Yes, I think it is correct, as you have it in your code.

Create a middleware and Apply middleware in middlewareRoute and add tenancy.enforce in the route/web.php

but it does not work.
