### ISSUE TITLE
The user and resetPassword migrations are not migrated

### ISSUE THREAD

**Issue by mnuhell** [ashokgelal/townhouse#5]
Hi,  I have a problem with the migrations, when run `php artisan tenancy:install` run customer, websites, and hostname are migrated, but the user and passwordResets are not migrated because they are into tenant folder when run `php artisan migrate`

Thanks

**Comment by nathansiafa** [comment]
Try creating a tenant and see if it throws any errors.

**Comment by mnuhell** [comment]
The tenant are created and deleted fine, without error.

**Comment by nathansiafa** [comment]
Do you have the password resets tables in the tenants folder?

**Comment by mnuhell** [comment]
Yes, How say the post. 

![captura de pantalla 2018-02-09 13 55 44](https://user-images.githubusercontent.com/558183/36029045-daa0f9ba-0da1-11e8-9136-ce87f9cb35ec.png)

**Comment by nathansiafa** [comment]
Do you have the tenants database created? Check your database server for some random generated uuid.

**Comment by mnuhell** [comment]
When I run `php artisan tenancy:migrate:refresh` show 
<img width="627" alt="captura de pantalla 2018-02-09 14 29 25" src="https://user-images.githubusercontent.com/558183/36029997-c91c3d0e-0da5-11e8-805c-3b49f77cbab4.png">
But when run `php artisan tenancy:migrate` this
`Nothing to migrate.`

In the database show when I create a Tenant with `php artisan tenant:create improve improve@improve.com`
![captura de pantalla 2018-02-09 14 35 55](https://user-images.githubusercontent.com/558183/36030219-9878df1c-0da6-11e8-8f77-6b02f9a112c1.png)

**Comment by nathansiafa** [comment]
The **uuid** column in the websites table please check you database server(sequel pro I guess) if a database exist with that name.

**Comment by mnuhell** [comment]
Is correct show the uuid database
![captura de pantalla 2018-02-09 14 44 22](https://user-images.githubusercontent.com/558183/36030506-cd953cd0-0da7-11e8-8599-31c188dd928e.png)

**Comment by nathansiafa** [comment]
And I do see all the tables.

**Comment by mnuhell** [comment]
Now Work fine @nathansiafa  Thanks!! 

Now i have this [issue](https://github.com/ashokgelal/townhouse/issues/4)

**Comment by nathansiafa** [comment]
Glad to help :smile:
