### ISSUE TITLE
There are no commands defined in 'tenant' namespace

### ISSUE THREAD

**Issue by swati-clarion** [ashokgelal/townhouse#6]
I successfully installed tenancy using php artisan tenancy:install

The class CreateTenant is also created at app\Console\Commands\CreateTenant.php

I also added these in providers in app.php
// Hyn multi tenancy.
Hyn\Tenancy\Providers\Tenants\ConfigurationProvider::class,
Hyn\Tenancy\Providers\TenancyProvider::class,
// Hyn multi tenancy webserver integration.
Hyn\Tenancy\Providers\WebserverProvider::class,

and added this in Kernel.php,

protected $commands = [
// Commands\CreateTenant::class
'App\Console\Commands\CreateTenant'
];

But when I run php artisan tenant:create gc gc@example.com , I get error "There are no commands defined in "tenant" namespace.

I have cleared config cache many times, but still same error. Please guide what am I missing here.

Thanks

**Comment by mnuhell** [comment]
Hi, @swati-clarion 
that you have not changed the name of your application and instead of being in the protected $commands
"App\" to "you app name"

**Comment by swati-clarion** [comment]
Hi mnuhell,

I got the issue. Actually the CreateTenant.php class file was not copied properly from Ashok's tutorial. I was using old file. Now , its working.

Thanks for your help.

**Comment by mnuhell** [comment]
Great!! @swati-clarion

**Comment by ashokgelal** [comment]
Glad to hear that you figured it out. Thanks for jumping in, @mnuhell
