### ISSUE TITLE
Middleware only in subdomain

### ISSUE THREAD

**Issue by mnuhell** [ashokgelal/townhouse#7]
Hi, 
I have a question, in the middleware enforce.tenancy is by default for all tenants, but 
I would like that only was for the subdomain url subdomain.domain.com, 
for the domain.com middleware It should be web.

How I can change in the EnforceTenancy middleware?

Thanks!!

**Comment by Astriel** [comment]
Hello @mnuhell : did you find an answer by any chance ? I'm facing the same problem ! 

Thanks !
