### ISSUE TITLE
Getting... "This site can’t be reached"

### ISSUE THREAD

**Issue by anil1712** [ashokgelal/townhouse#8]
Hi 
I followed all the steps in my system (W10, Apache2 and MySQL) but when I try to open `boise.townhouse.dev` in browser then its not showing any page for me and its redirecting to `https` also.

Do I need to add vhost in apache to make it work? 

Thanks,
Anil

**Comment by anil1712** [comment]
@ashokgelal Can you please provide some readme to run this project

**Comment by StuBez** [comment]
Google bought the .dev gTLD, and Chrome and Firefox now redirect all *.dev traffic to HTTPS.

I assume you're using Valet, which used to default to .dev domains. Try running `valet domain test` in your terminal. After that, you should be able to visit http://boise.townhouse.test.

**Comment by chrishud2011** [comment]
I spent most of the day on this project and getting the same results as @anil1712. I created 2 projects from scratch before cloning the repo and can't connect to subdomain on any. Using Homestead and .test extension. I get chris.townhouse.test refused to connect from both the subdomain directly and the email, at both http and https.

**Comment by ashokgelal** [comment]
What operating system are you using to run the project?

**Comment by chrishud2011** [comment]
PRETTY_NAME="Ubuntu 16.04.2 LTS"

**Comment by ashokgelal** [comment]
Unfortunately, I'm on Mac and using valet. I've never used Homestead so I don't know how to configure it to support subdomains. You may have to configure your /etc/hosts file and/or homestead.yml file. There seems to be plenty of articles online on how to configure Homestead for supporting subdomains (such as this discussion: https://laracasts.com/discuss/channels/general-discussion/homestead-and-subdomains)

I don't think this is the problem with the project itself.

**Comment by chrishud2011** [comment]
Ahh. You were right. For anyone else who stumbles upon this, it is still necessary to define the subdomain in the /etc/hosts and homestead.yaml files

**Comment by ashokgelal** [comment]
Awesome! Glad you got it working!!
